apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: podummy
  namespace: metallb-system
spec:
  addresses:
    - 10.5.16.140-10.5.16.140
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: podummy
  namespace: metallb-system
